config/routes.rb
Rails.application.routes.draw do
  root to: "sessions#new"

  get     'login',   to: 'sessions#new'
  post    'login',   to: 'sessions#create'
  delete  'logout',  to: 'sessions#destroy'



  resources :blogs do
    collection do
      get 'top'
      post 'confirm'
    end
  end
  resources :users
  get '/users/favo/:id', to:'users#favo'
  resources :sessions, only: [:new, :create, :destroy]
  resources :favorites, only: [:index, :create, :destroy]
  
  mount LetterOpenerWeb::Engine, at: "/letter" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
    validates :title,:content,presence: true, length: { in: 1..140 }
    #validates :image, presence: true
    has_many :favorites, dependent: :destroy
    has_many :favorite_users, through: :favorites, source: :user
    belongs_to :user
    
    mount_uploader :image, ImageUploader
end

app/models/contact.rb
class Contact< ApplicationRecord
  include ActiveModel::Model

  attr_accessor :name, :tel, :email, :content
  
	validates :name, presence: true
	validates :tel, presence: false, numericality: true
	validates :email, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :blog
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
    #user情報を登録するためのデータベース
    validates :name, presence: true, length: { maximum: 30}
    validates :email, presence: true, length: { maximum: 255},
                     format: {with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                     uniqueness: true
    before_validation{ email.downcase! }
    has_secure_password
    
    validates :password, presence: true, length:{ minimum:6 }
    has_many :favorites, dependent: :destroy
    has_many :favorite_blog, through: :favorites, source: :blog
    has_many :blogs
    
    mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  before_action :set_current_user
  
  def set_current_user
    @current_user = User.find_by(id: session[:user_id])
  end
  
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
    before_action :set_blog, only: [:show, :edit, :update ,:destroy]
    before_action :must_login, only:[:show, :edit,:destroy]
    before_action :must_login, except: [:top]
    def top
    end
    
    def index
        @blogs = Blog.all
        logged_in?
    end
    
    def show
        @favorite = current_user.favorites.find_by(blog_id: @blog.id)
    end

    def new
      @blogs = Blog.all
      @blog = Blog.new
       if params[:back]
        @blog = Blog.new(blog_params)
        redirect_to '/blogs/new'
       end
    end

    def create
        @blog = Blog.create(blog_params)
        @blog.user_id = current_user.id
        
        if @blog.save
            ContactMailer.contact_mail(@blog).deliver
            redirect_to blogs_path, notice: "ブログを作成しました"
        else
            render 'new'
        end
    end
    
    def edit
    end
    
    def update
        if @blog.update(blog_params)
            redirect_to blogs_path, notice:"ブログを編集しました"
        else
            render'edit'
        end
    end
        
    def destroy
        @blog.destroy
        redirect_to blogs_path, notice:"ブログを削除しました"
    end
    
    def confirm
        @blog = Blog.new(blog_params)
        @blog.user_id = current_user.id
        render :new if @blog.invalid?
    end
    
    
    private
    def blog_params
        #params.require(:blog).permit(:title, :content, :image, :image_cache)
        params.require(:blog).permit(:title, :content)
    end
    
    def set_blog
        @blog = Blog.find(params[:id])
    end
    
    def must_login
       if current_user.nil?
         redirect_to root_path, notice: "ログインしてください"
       end
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        ContactMailer.contact_mail(@contact).deliver
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_contact
    @contact = Contact.find(params[:id])
  end

  def contact_params
    params.require(:contact).permit(:name, :email, :content)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  
  def create
      favorite = current_user.favorites.create(blog_id: params[:blog_id])
      redirect_to blogs_url, notice: "ブログをお気に入りに登録しました"
  end
  
  def destroy
      favorite = current_user.favorites.find_by(id: params[:id]).destroy
      redirect_to blogs_url, notice: "ブログをお気に入りに解除しました"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  #skip_before_action :user_logged_in? 
  
  def new
  end
  
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      log_in(user)
      current_user
      redirect_to root_path(user.id),notice:'ログインしました'
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render 'new'
    end
      
  end
  
  def destroy
    log_out if logged_in?
    session.delete(:user_id)
    flash[:notice] = "ログアウトしました"
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user , only:[:favo, :edit, :update]
    #before_action :set_user
    
    def new
        unless logged_in?
          @user = User.new
        else
          redirect_to root_path,notice:'すでにログインしています。'
        end
    end
    
    def favo
        @favorites_blogs = @user.favorite_blog
    end
    
    def create
        @user = User.new(user_params)
        if @user.save
            redirect_to user_path(@user.id)
        else
            render 'new'
        end
    end
   
   def edit
   end
   
   def update
       if @user.update(user_params)
            redirect_to user_path, notice:"アイコンを編集しました"
       else
            render'edit'
       end
   end
    
    def show
        @user = User.find(params[:id])
    end
    
    private
    def user_params
        params.require(:user).permit(:name, :email, :password,
                                     :password_confirmation, :image, :image_cache)
    end
    
    def set_user
        @user = User.find_by(id: params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
    def choose_new_or_edit
      if action_name == 'new' || action_name == 'confirm'
        confirm_blogs_path
      elsif action_name == 'edit'
        blog_path
      end
    end
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        if session[:user_id].present?
          @current_user ||= User.find_by(id: session[:user_id])
        end
    end
    
    def logged_in?
        current_user.present?
    end
    
    def log_in(user)
        session[:user_id] = user.id
    end
    
    def log_out
        session[:user_id] = nil
        @current_user = nil
    end
    
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_form.html.erb
<div class="container">
<%= form_with(model: @blog, local: true ,url: choose_new_or_edit ) do |form| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= @blog.errors.count %>件のエラーがあります。</h2>
      <ul>
      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
      <div>
       <%= form.label :タイトル %><br>
       <%= form.text_field :title,:size=>"90" %>
      </div>
      <div>
       <%= form.label :内容 %><br>
       <%= form.text_area :content ,:size=>"90x20" %>
      </div>
  <div class="field">
    <%#= form.label :画像 %>
    <%#= image_tag(@blog.image.url , :size =>'320x320') if @blog.image.url %>
    <%#= form.file_field :image %>
  </div>
<%= form.submit name="送信する" %>
<% end %>
</div>
<%= link_to "ブログ一覧画面にもどる", blogs_path %>

app/views/blogs/confirm.html.erb
<h3>以下の内容で、送信する。</h3>

<%= form_with(model: @blog, url: blogs_path, local: true) do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <%= form.hidden_field :image %>

  <p>タイトル:<%= @blog.title %></p>
  <p>本文:<%= @blog.content %></p>
  <p><%= image_tag(@blog.image.url ,:size =>'340x340') if @blog.image.url %></p>
  <%= form.hidden_field :image_cache %>
  
  
  <%= form.submit  "登録する" %>
<% end %>

<%= form_with(model: @blog, url: new_blog_path, local: true, method: 'get') do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <%= form.submit "もどる",name: 'back' %>
<% end %>

app/views/blogs/edit.html.erb
<h1>ブログを編集する</h1>

<%= render 'form' %>

app/views/blogs/index.html.erb
<h1>ブログ一覧</h1>
   
   <div class="contents">
   <div class="row">
      
    <div class="col-md-6">
      <div class="row_B">
        <h3>ブログ一覧の見方<h3>
        <p>aaaaaaaaaaaaaaaaaaaaaa</p>
        <p>aaaaaaaaaaaaaaaaaaaaaa</p>
        <p>aaaaaaaaaaaaaaaaaaaaaa</p>
        <p>aaaaaaaaaaaaaaaaaaaaaa</p>
      </div>
    </div>
      
    <div class="col-md-6">
         <ul class="row_A" id="top_content">
           <li class="col-sm-12 col-md-5">説明１</li>
           <li class="col-sm-12 col-md-5">説明２</li>
           <li class="col-sm-12 col-md-5">説明３</li>
           <li class="col-sm-12 col-md-5">説明４</li>
         </ul>
    </div>

    
   </div>
  </div>
   
   
   
   <div class="contents">
   <% @blogs.each do |blog| %>
     <div class="row">
      <div class="col-sm-12">
         <div class="index_title">
           <%= blog.title %>
         </div>
       
         <div class="index_content">
           <%= blog.content %>
         </div>
        
         <%= link_to '詳細確認',blog_path(blog.id), class: 'btn btn-info' %>
       
        <% if blog.user_id == current_user.id %>
         <%= link_to "編集する", edit_blog_path(blog.id) ,data: { confirm: '本当に編集していいですか？'}, class: 'btn btn-success'%>
         <%= link_to '削除する', blog_path(blog.id), method: :delete,data: { confirm: '本当に削除していいですか？'}, class: 'btn btn-danger'%>
        <% end %>
      </div>
      </div>
   <% end %>
   
</div>
</div>
<br><br>
<%= link_to '新しくブログを投稿する', new_blog_path, class: 'btn btn-default' %>

app/views/blogs/new.html.erb
<h2>ブログを作成する</h2>

  <%= render 'form' %>

app/views/blogs/show.html.erb
<h1>ブログ詳細画面</h1>
<p>タイトル: <%= @blog.title %></p>
<p>内容: <%= @blog.content %></p>
<p><%#= image_tag(@blog.image.url , :size =>'320x480') if @blog.image.url %></p>

<% unless @blog.user_id == current_user.id  %>
  <% if @favorite.present? %>
    <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'お気に入りする', favorites_path(blog_id: @blog.id), method: :post, class: 'btn btn-primary' %>
  <% end %>
<% end %>

<%= link_to "ブログ一覧画面にもどる", blogs_path %>
<br>

app/views/blogs/top.html.erb
<div class="col-sm-12" id = "header_img">
    <%= image_tag "top.jpg", class:"img-responsive" %>
</div>

<article>
  <div class="contents">
   <div class="row">
      
    <div class="col-md-6">
         <ul class="row_A" id="top_content">
           <li class="col-sm-12 col-md-5">dive-into-code</li>
           <li class="col-sm-12 col-md-5">eeeeeeeeeeeeee</li>
           <li class="col-sm-12 col-md-5">aaaaaaaaaaaaaa</li>
           <li class="col-sm-12 col-md-5">bbbbbbbbbbbbbb</li>
         </ul>
    </div>
    
    <div class="col-md-6">
      <div class="row_B">
        <h3>シリーズ課題3<h3>
        <p>aaaaaaaaaaaaaaaaaaaaaa</p>
        <p>aaaaaaaaaaaaaaaaaaaaaa</p>
        <p>aaaaaaaaaaaaaaaaaaaaaa</p>
        <p>aaaaaaaaaaaaaaaaaaaaaa</p>
      </div>
    </div>
    
   </div>
  </div>
</article>
<div class="push_top"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kadai2</title>
    <%= csrf_meta_tags %>
    
    <meta name="viewport" content="width=device-width">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    
  <div class="container-fluid">
       
    <header class = "header">
      <nav class="navbar navbar-default">
          <div class="navbar-header">
             <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#gnavi">
               <span class="sr-only">Twitterクローン</span>
               <span class="icon-bar"></span>
               <span class="icon-bar"></span>
               <span class="icon-bar"></span>
             </button>
          </div>
    
          <div id="gnavi" class="collapse navbar-collapse">
             <ul class="nav navbar-nav">
               <li><a href="/blogs/top" >Top</a></li>
               
               <% if logged_in? %>
                 <li><%= link_to "新規投稿", new_blog_path(current_user.id)%></li>
                 <!--<li><%= link_to "ブログ一覧", blogs_path(current_user.id), method: :delete%></li>-->
               <% end %>
          </div>
      </nav>
    </header>
    
    
    <div id="sign">
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}")%>
    <% end %>
    
    <% if logged_in? %>
    <ul>
      <li><%= link_to "プロフィール",user_path(current_user.id), class: 'btn btn-default'%></li>
      <li><%= link_to "ログアウト", session_path(current_user.id),method: :delete, class: 'btn btn-default'%></li>
    <% else %>
      <li><%= link_to "会員登録", new_user_path, class: 'btn btn-default'%></li>
      <li><%= link_to "ログイン", new_session_path, class: 'btn btn-default'%></li>
    <% end %>
    </ul>
    </div>
    
    
     <%= yield %>
    
    
    <div class="push"></div>
    
    <footer  id="footer" class="col-sm-12">
      <p>2018年6月期funato</p>
    </footer>
  </div>
</html>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>  
  
  <div>
    名前　　　　　
    <%= f.text_field :name %>
  </div>
  <div>
    メールアドレス
    <%= f.email_field :email %>
  </div>
  <div>
    パスワード　　
    <%= f.password_field :password %>
  </div>
  <div>
    パスワード確認
    <%= f.password_field :password_confirmation %>
  </div>
  
   <div class="field">
    <%= f.label :アイコン %>
    <div id="icon"><%= image_tag(@user.image.url, :size =>'160x160') if @user.image.url %></div>
    <%= f.file_field :image %>
  </div>
  
  <br>
  <%= f.submit "アカウントの作成" %>
<% end %>

app/views/users/edit.html.erb
<%= render 'form'  %>

app/views/users/favo.html.erb
<h1>お気に入り一覧</h1>


<div class="container">
  <% @favorites_blogs.each do |favo| %>
    <div class="row">
       <div class="index_title">
         <%= favo.title %>
       </div>
       <div class="index_content">
         <%= favo.content %>
       </div>
    </div>
<% end %>
<br>
<%= link_to 'プロフィール画面', user_path(current_user.id), class: 'btn btn-default' %>

app/views/users/new.html.erb
<h1>会員登録</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>  
  
  <div>
    名前　　　　　
    <%= f.text_field :name %>
  </div>
  <div>
    メールアドレス
    <%= f.email_field :email %>
  </div>
  <div>
    パスワード　　
    <%= f.password_field :password %>
  </div>
  <div>
    パスワード確認
    <%= f.password_field :password_confirmation %>
  </div>
  <br>
  <%= f.submit "アカウントの作成" %>
<% end %>

app/views/users/show.html.erb
<!--ログイン成功時のページ-->
<h1><%= @user.name %>のページ</h1>


  <p>メールアドレス: <%= @user.email %></p>


   <strong>アイコン</strong>
  <div id="icon"><%= image_tag(@user.image.url, :size =>'180x180') if @user.image.url %></div>

<%=link_to "新規投稿",new_blog_path    %>
<%=link_to "ブログ一覧", blogs_path   %>
<li><%= link_to "お気に入り一覧", :controller => "users",:action => "favo", class: 'btn btn-default'%></li>
<%=link_to "アイコン登録",edit_user_path  %>